[tts.eleven]
enabled = false
voice_name = "Patrick"
model_type = "eleven_multilingual_v1"
ffmpeg_available = false

[tts.azure]
enabled = false
voice_name = "en-US-TonyNeural"
override_device_id = false
device_id = ""

[tts.bark]
enabled = false
voice_name = "v2/en_speaker_6"
stream = false
stream_preload = 2

[stt.azure]
enabled = false
push_to_talk = true
override_device_id = false
device_id = ""

[stt.sphinx]
enabled = false
pause_threshold = 1.5
energy_threshold = 300
auto_calibrate = true
override_device_index = false
device_index = 0

[game]
grade_level = "1st"
local_nationality = "American"

[openai]
bypass = false
model_name = "gpt-4"
per_response_max_tokens = 1024
use_history = true
history_max_sets = 5

[logging]
level = "WARNING"

[ai_personality]
name = "Patrick"
role_base = "insurance"
role = "insurance salesman"
role_desc = "an insurance salesman and really like your job and are the head of your department" # You are...
likes_to_reference = "insurance business and salesman skills" # You occasionally reference your...
love_and_pride = "your insurance job" # You love...and are incredibly proud of it
hope_for_player = "shopping for insurance" # You hope that the person you are conversing with is having a great time...
personality_extra = "" # Extra personality request, i.e. "Sometimes you act like you're falling in love with the player."
