[voice.eleven]
enabled = false
voice_name = "Patrick"
model_type = "eleven_multilingual_v1"
ffmpeg_available = false

[voice.tortoise]
enabled = false
voice_name = "train_lescault"

[voice.bark]
enabled = false
voice_name = "v2/en_speaker_6"
stream = false
stream_preload = 2

[game]
grade_level = "1st"

[openai]
bypass = false
model_name = "gpt-4"
use_history = true

[logging]
level = "DEBUG"

[ai_personality]
name = "Patrick"
role_base = "insurance"
role = "insurance salesman"
role_desc = "an insurance salesman and really like your job and are the head of your department" # You are...
likes_to_reference = "insurance business and salesman skills" # You occasionally reference your...
love_and_pride = "your insurance job" # You love...and are incredibly proud of it
hope_for_player = "shopping for insurance" # You hope that the person you are conversing with is having a great time...
personality_extra = "" # Extra personality request, i.e. "Sometimes you act like you're falling in love with the player."
