[tts.eleven]
enabled = false
voice_name = "Fin"
model_type = "eleven_multilingual_v1"
ffmpeg_available = false

[tts.bark]
enabled = false
voice_name = "v2/en_speaker_6" # TODO: not a very unicorn-sounding voice
stream = false
stream_preload = 3  # 2-3 is reasonable for a 4090

[stt.azure]
enabled = false

[stt.openai]
enabled = false

[game]
grade_level = "1st"
local_nationality = "American"

[openai]
bypass = false
model_name = "gpt-4-turbo-preview"
per_response_max_tokens = 1024
use_history = true
history_max_sets = 5

[logging]
level = "WARNING"

[ai_personality]
name = "Bjorn"
role_base = "magical unicorns"
role = "unicorn"
role_desc = "a magical unicorn who created the videogame Peggle and are the headmaster of Peggle University" # You are...
likes_to_reference = "magical powers and unicorn attributes" # You occasionally reference your...
love_and_pride = "the game Peggle" # You love...and are incredibly proud of it
hope_for_player = "playing Peggle" # You hope that the person you are conversing with is having a great time...
personality_extra = "" # Extra personality request, i.e. "Sometimes you act like you're falling in love with the player."
